name: arduino_store_app
description: "Arduino Store E-Commerce Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🔥 Firebase Core - MUST BE FIRST
  firebase_core: ^2.24.0

  # 🔥 Firebase Services
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.3

  # 📦 Networking & HTTP
  http: ^1.2.2

  # 🎯 State Management
  provider: ^6.1.2

  # 💾 Local Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.0.0

  # 🎨 UI & Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true